### ISSUE TITLE
Multiple errors on vagrant up

### ISSUE THREAD

**Issue by zorel** [vangj/vagrant-hadoop-2.3.0#2]
Hello.

https://gist.github.com/zorel/10734573 for complete output.

I have encountered several chown issues when running vagrant up. Some services are up, some not.

KO:    NameNode
OK:    DataNode
OK:    ResourceManager
OK:    NodeManager
KO:    JobHistory

Running vagrant 1.4.3 with VBox 4.2.18_OSEr88780, on OpenSuse 13.1

**Comment by vangj** [comment]
yes, i'm seeing those chown issues too. but all the services are still running. i looked at your output and i don't see that the namenode format has actually finished successfully. there might be two issues (or even three) going here. 
1. chown issue
2. namenode format issue
3. running this from windows (me) vs opensuse (you)

i'll try to track down the chown issue.

**Comment by vangj** [comment]
when typing

```
sudo service hadoop start
```

i see chown issues with

```
$HADOOP_YARN_HOME/sbin/yarn-daemon.sh start proxyserver --config $HADOOP_CONF_DIR
$HADOOP_PREFIX/sbin/mr-jobhistory-daemon.sh start historyserver --config $HADOOP_CONF_DIR
```

the chown issues shows up on the console as the following.

```
chown: missing operand after /usr/local/hadoop-2.3.0/logs
```

look at $HADOOP/sbin/yarn-daemon.sh on line 84.
look at $HADOOP/sbin/mr-jobhistory-daemon.sh on line 82.

the code in yarn-daemon.sh tries to set the value of YARN_IDENT_STRING.

```
if [ "$YARN_IDENT_STRING" = "" ]; then
  export YARN_IDENT_STRING="$USER"
fi
```

likewise, the code in mr-jobhistory-daemon.sh tries to set the value of HADOOP_MAPRED_IDENT_STRING.

```
if [ "$HADOOP_MAPRED_IDENT_STRING" = "" ]; then
  export HADOOP_MAPRED_IDENT_STRING="$USER"
fi
```

for some reason, $USER itself is empty, so when calling the chown command, there is no user passed in and so the chown issue described in this ticket is observed.
